---
# Homepage configuration
# See https://fontawesome.com/v5/search for icons options

title: "Mluvii"
subtitle: "All mluvii service"
logo: "assets/png/mluvii.png"
# icon: "fas fa-skull-crossbones" # Optional icon

header: true
footer: false #'<p>Created with <span class="has-text-danger">❤️</span> with <a href="https://bulma.io/">bulma</a>, <a href="https://vuejs.org/">vuejs</a> & <a href="https://fontawesome.com/">font awesome</a> // Fork me on <a href="https://github.com/bastienwirtz/homer"><i class="fab fa-github-alt"></i></a></p>' # set false if you want to hide it.

# Optional theme customization
theme: default
colors:
  light:
    highlight-primary: "#3367d6"
    highlight-secondary: "#4285f4"
    highlight-hover: "#5a95f5"
    background: "#f5f5f5"
    card-background: "#ffffff"
    text: "#363636"
    text-header: "#ffffff"
    text-title: "#303030"
    text-subtitle: "#424242"
    card-shadow: rgba(0, 0, 0, 0.1)
    link: "#3273dc"
    link-hover: "#363636"
  dark:
    highlight-primary: "#3367d6"
    highlight-secondary: "#4285f4"
    highlight-hover: "#5a95f5"
    background: "#131313"
    card-background: "#2b2b2b"
    text: "#eaeaea"
    text-header: "#ffffff"
    text-title: "#fafafa"
    text-subtitle: "#f5f5f5"
    card-shadow: rgba(0, 0, 0, 0.4)
    link: "#3273dc"
    link-hover: "#ffdd57"

# Optional message
message:
  #url: https://b4bz.io
  style: "is-dark" # See https://bulma.io/documentation/components/message/#colors for styling options.
  title: "Here should be all mluvii services!"
  icon: "fa fa-grin"
  content: "Alright, mluvii rockstars! Dive headfirst into the Homer Service - our shiny new toy post-merger! 🚀 Think of it as the ultimate backstage pass to streamlining our groovy processes. Whether it's data shenanigans, task magic, or just about any rock-n-roll operation, Homer's got your back. So, as we navigate this grand corporate concert together, let's hit the right notes with Homer and bring the house down! 🎸"

# Optional navbar

links:
  [] # Allows for navbar (dark mode, layout, and search) without any links
  #- name: "Contribute"
  #  icon: "fab fa-github"
  #  url: "https://github.com/bastienwirtz/homer"
  #  target: "_blank" # optional html a tag target attribute
  #- name: "Wiki"
  #  icon: "fas fa-book"
  #  url: "https://www.wikipedia.org/"
  # this will link to a second homer page that will load config from additional-page.yml and keep default config values as in config.yml file
  # see url field and assets/additional-page.yml.dist used in this example:
  #- name: "another page!"
  #  icon: "fas fa-file-alt"
  #  url: "#additional-page"

# Services
# First level array represent a group.
# Leave only a "items" key if not using group (group name, icon & tagstyle are optional, section separation will not be displayed).
services:
  - name: "O2 ITS"
    icon: "fa-solid fa-building"
    items:
      - name: "INTRANET O2 (VPN needed)"
        logo: "assets/png/o2.png"
        subtitle: "O2 internal information."
        tag: "o2"
        url: "http://intranet.o2.cz/"
        target: "_blank"
      - name: "Target"
        logo: "assets/png/target.png"
        subtitle: "Workforce management"
        tag: "o2"
        url: "https://tos.o2its.cz/TOS/Target2100_PersonSeznamZamestnancu.aspx"
        target: "_blank"
      - name: "O2 SSP"
        logo: "assets/png/o2.png"
        subtitle: "System for entering requests"
        tag: "o2"
        url: "https://ssp.cz.o2/ssp/index.jsp?init"
        target: "_blank"

  - name: "Documentation"
    icon: "fa-solid fa-book"
    items:
      - name: "Internal documentation"
        logo: "assets/png/confluence.png"
        subtitle: "Confluence - Technical description of mluvii"
        tag: "doc"
        url: "https://mluvii.atlassian.net/wiki/spaces/IT/overview"
        target: "_blank"
      - name: "JIRA"
        logo: "assets/png/jira.png"
        subtitle: "Issue tracker"
        tag: "doc"
        url: "https://mluvii.atlassian.net/jira/software/c/projects/M3/boards/23"
        target: "_blank"
      - name: "Public documentation"
        logo: "assets/png/mluvii.png"
        subtitle: "Public documentation for external users. Editable on https://app.gitbook.com/"
        tag: "doc"
        url: "https://docs.mluvii.com/"
        target: "_blank"

  - name: "Repository"
    icon: "fa-solid fa-box-archive"
    items:
      - name: "GitLab"
        logo: "assets/png/gitlab.png"
        subtitle: "Main mluvii repository"
        tag: "repo"
        url: "https://git.icord.cz/"
        target: "_blank"
      - name: "GitHub"
        logo: "assets/png/github.png"
        subtitle: "Public mluvii repository"
        tag: "repo"
        url: "https://github.com/mluvii"
        target: "_blank"

  - name: "Statistics"
    icon: "fa-solid fa-chart-area"
    items:
      - name: "CRM Statistics"
        logo: "assets/png/mluvii.png"
        subtitle: "Internal mluvii metrics"
        tag: "stat"
        url: "https://stat.intranet.mluvii.com/crm/"
        target: "_blank"
      - name: "Grafana"
        logo: "assets/png/grafana.png"
        subtitle: "Servers monitoring"
        tag: "stat"
        url: "https://grafana.intranet.mluvii.com/"
        target: "_blank"
      - name: "InfluxDB"
        logo: "assets/png/influx.png"
        subtitle: "Time series DB"
        tag: "stat"
        url: "https://influxdb.mluvii.com/"
        target: "_blank"  

  - name: "Cloud"
    icon: "fa-solid fa-cloud"
    items:
      - name: "DigitalOcean"
        logo: "assets/png/digitalocean.png"
        subtitle: "Main mluvii cloud (k8s)"
        tag: "cloud"
        url: "https://cloud.digitalocean.com/projects/6ffd9bb4-18a4-4ea1-80ec-359596d10a25/resources?i=76f575"
        target: "_blank"
      - name: "Azure"
        logo: "assets/png/azure.png"
        subtitle: "O2 services and API GW"
        tag: "cloud"
        url: "https://portal.azure.com/#home"
        target: "_blank"
      - name: "VMware"
        logo: "assets/png/vmware.png"
        subtitle: "Phone architecture"
        tag: "cloud"
        url: "https://cloud2.o2.cz/tenant/mluviicom/vdcs"
        target: "_blank"

  - name: "Debugging"
    icon: "fa-solid fa-bug"
    items:
      - name: "testRTC"
        logo: "assets/png/testrtc.png"
        subtitle: "Monitoring webrtc"
        tag: "bug"
        url: "https://app.testrtc.com/app/monitoring/history?page=1"
        target: "_blank"
      - name: "Sentry"
        logo: "assets/png/sentry.png"
        subtitle: "Frontend monitoring"
        tag: "bug"
        url: "https://sentry.mluvii.com/organizations/mluvii/projects/"
        target: "_blank"
      - name: "Seq"
        logo: "assets/png/seq.png"
        subtitle: "Backend logs"
        tag: "bug"
        url: "https://seq.mluvii.com/#/login"
        target: "_blank"

  - name: "QA software"
    icon: "fa-solid fa-flask-vial"
    items:
      - name: "CrossBrowserTesting App"
        logo: "assets/png/crossbrowsertesting.png"
        subtitle: "Testing on different browsers"
        tag: "qa"
        url: "https://app.crossbrowsertesting.com/login"
        target: "_blank"
      - name: "TestRail"
        logo: "assets/png/TestRail.png"
        subtitle: "Test automation"
        tag: "qa"
        url: "https://mluvii.testrail.io/index.php?/projects/overview/7"
        target: "_blank"
      - name: "Kobiton"
        logo: "assets/png/kobiton.png"
        subtitle: "mobile testing"
        tag: "qa"
        url: "https://portal.kobiton.com/devices"
        target: "_blank"

  - name: "Design"
    icon: "fa-brands fa-figma"
    items:
      - name: "Figma"
        logo: "assets/png/figma.png"
        subtitle: "Collaborative browser-based interface design tool"
        tag: "design"
        url: "https://www.figma.com/files/recent?fuid=647764407216263850"
        target: "_blank"
      - name: "Envato"
        logo: "assets/png/envato.png"
        subtitle: "Video Templates, WP Themes, Photos, Graphic Templates"
        tag: "design"
        url: "https://elements.envato.com/"
        target: "_blank"

  - name: "Production services"
    icon: "fa-solid fa-umbrella"
    items:
      - name: "Mluvii - Saas"
        logo: "assets/png/mluvii.png"
        subtitle: "Production application"
        tag: "prod"
        url: "https://git.icord.cz/"
        target: "_blank"
      - name: "CSOB"
        logo: "assets/png/csob.png"
        subtitle: "Production application"
        tag: "prod"
        url: "https://mluvii.csob.cz/app"
        target: "_blank"
      - name: "HC Kazakhstan"
        logo: "assets/png/homecredit.png"
        subtitle: "Production application"
        tag: "prod"
        url: "https://chat.homecredit.kz/"
        target: "_blank"
      - name: "O2 CZ"
        logo: "assets/png/o2.png"
        subtitle: "Production application"
        tag: "prod"
        url: "https://virtualni-prodejna.o2.cz/"
        target: "_blank"

  - name: "Developers environment"
    icon: "fa-brands fa-dev"
    items:
      - name: "AppTest"
        logo: "assets/png/mluvii.png"
        subtitle: "Mluvii pre-production enviroment"
        tag: "dev"
        url: "https://apptest.mluvii.com/"
        target: "_blank"
      - name: "AppDev"
        logo: "assets/png/mluvii.png"
        subtitle: "Mluvii development enviroment"
        tag: "dev"
        url: "https://appdev.mluvii.com/"
        target: "_blank"
      - name: "Ptr"
        logo: "assets/png/mluvii.png"
        subtitle: "Mluvii development enviroment with production data"
        tag: "dev"
        url: "https://ptr.mluvii.com/"
        target: "_blank"
      - name: "O2 test"
        logo: "assets/png/o2.png"
        subtitle: "O2 test"
        tag: "dev"
        url: "https://o2test.mluvii.com/"
        target: "_blank"
      - name: "CSOB pre-production enviroment"
        logo: "assets/png/csob.png"
        subtitle: "CSOB "
        tag: "dev"
        url: "https://test.mluvii.csob.cz/"
        target: "_blank"

  - name: "Others"
    icon: "fa-solid fa-font-awesome"
    items:
      - name: "Rundeck"
        logo: "assets/png/rundeck.png"
        subtitle: "Runbook automation platform"
        tag: "others"
        url: "https://rundeck.intranet.mluvii.com/project/Statistics/jobs"
        target: "_blank"
      - name: "TeamCity"
        logo: "assets/png/teamcity.png"
        subtitle: "Build management and continuous integration server"
        tag: "others"
        url: "https://tc.intranet.mluvii.com/"
        target: "_blank"
      - name: "Docker"
        logo: "assets/png/docker.png"
        subtitle: "Mluvii dockers"
        tag: "others"
        url: "https://hub.docker.com/repository/docker/icord/mluvii-dotnet"
        target: "_blank"
      - name: "Unifi"
        logo: "assets/png/unifi.png"
        subtitle: "Networking"
        tag: "others"
        url: "https://unifi.intranet.mluvii.com/"
        target: "_blank"
      - name: "SiteGround"
        logo: "assets/png/siteground.png"
        subtitle: "Mluvii website hosting"
        tag: "others"
        url: "https://tools.siteground.com/dashboard?siteId=S2dyMllYZ01KUT09"
        target: "_blank"
